# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partida',
            old_name='data',
            new_name='data_partida',
        ),
    ]
