# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0004_auto_20160417_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='partida',
        ),
        migrations.AddField(
            model_name='resultado',
            name='partida',
            field=models.ManyToManyField(to='apostas.Partida'),
        ),
    ]
