# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apostas', '0005_auto_20160417_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aposta',
            old_name='times',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='resultado',
            old_name='time',
            new_name='times',
        ),
    ]
